#!/bin/sh

# TOOD: add an argument for fixing errors automatically

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running isort.."
# Run isort for each python project
git ls-files '*.py' | xargs -I {} isort --src-path="{}" --check-only --diff "{}"

echo "Running black.."
black --check --diff "$repository_path"

echo "Running pylint.."
pylint $(git ls-files '*.py')

echo "Running mypy.."
git ls-files '*.py' | xargs --max-lines=1 mypy

exit 0